// plugins/solid-js-pokedex/src/index.tsx
import { YalAppPlugin, YalPluginsConfig } from '@yal-app/types';
import { render } from 'solid-js/web';
import Pokedex from './Components/Pokedex';
import { setText } from './state';

function App() {
  return (
    <div class="mx-auto max-w-2xl py-10">
      <Pokedex />
    </div>
  );
}

const testSolidApp: YalAppPlugin = (args) => {
  const { appNode } = args;
  if (args.text !== '') {
    setText(args.text);
  }
  if (appNode.children.length === 0) {
    render(() => <App />, appNode);
  }
  return { appNode };
};

export const config: YalPluginsConfig = {
  keywords: 'pokemon',
  filter: false,
  debounce: true,
  isApp: true,
};

export default testSolidApp;

// plugins/react-pokedex/src/index.tsx
import { YalPluginsConfig, YalAppPlugin } from '@yal-app/types';
import React from 'react';
import ReactDOM from 'react-dom';
import { App } from './App';

const testReactApp: YalAppPlugin = (args) => {
  const { appNode } = args;

  ReactDOM.render(
    <React.StrictMode>
      <div className="mx-auto max-w-2xl py-32 sm:py-48 lg:py-56">
        <App text={args.text} />
      </div>
    </React.StrictMode>,
    appNode
  );
  return { appNode };
};

export const config: YalPluginsConfig = {
  keywords: 'react-pokemon',
  filter: false,
  isApp: true,
  debounce: true,
};

export default testReactApp;
